spring:
  sleuth:
    sampler:
      probability: 1.0
zuul:
  prefix: /api
  routes:
    BOOK-SERVICE:
      path: /book/**
    USER-SERVICE:
      path: /user/**
    LIBRARY-SERVICE:
      path: /library/**